# -*- coding: utf-8 -*-
"""Organized B1 speaking-topic content (bilingual EN/AR).

Source: three learner PDFs (Elementary word bank, Occupational course data,
Occupational synonyms). Reorganized alphabetical/level lists into themes.
"""

TOPICS = [
    {
        "id": "family", "num": 1,
        "en": "Personal Info & Family", "ar": "المعلومات الشخصية والعائلة",
        "talk": "عرّف عن نفسك وعائلتك: الاسم، العمر، مكان السكن، وأفراد الأسرة.",
        "groups": [
            ("Nouns", "أسماء", [
                ("name", "اسم"), ("age", "عمر"), ("address", "عنوان"),
                ("family", "عائلة"), ("mother", "أم"), ("father", "أب"),
                ("brother", "أخ"), ("sister", "أخت"), ("son", "ابن"),
                ("daughter", "ابنة"), ("parent", "والد/والدة"),
                ("grandfather", "جد"), ("grandmother", "جدة"),
                ("uncle", "عم / خال"), ("wife", "زوجة"), ("husband", "زوج"),
                ("baby", "طفل رضيع"), ("child", "طفل"), ("boy", "ولد"),
                ("girl", "فتاة"), ("friend", "صديق"), ("neighbor", "جار"),
                ("marriage", "زواج"), ("wedding", "زفاف"),
                ("birthday", "عيد ميلاد"), ("life", "حياة"), ("youth", "شباب"),
            ]),
            ("Verbs", "أفعال", [
                ("be", "يكون"), ("have", "يملك / لديه"), ("live", "يعيش"),
                ("love", "يحب"), ("know", "يعرف"), ("meet", "يلتقي"),
                ("grow up", "ينشأ / يكبر"), ("marry", "يتزوج"),
            ]),
            ("Adjectives", "صفات", [
                ("young", "شاب / صغير"), ("old", "كبير في السن"),
                ("single", "أعزب"), ("married", "متزوج"), ("kind", "لطيف"),
                ("honest", "صادق"), ("humble", "متواضع"), ("famous", "مشهور"),
            ]),
        ],
        "phrases": [
            ("What's your name?", "ما اسمك؟"),
            ("How old are you?", "كم عمرك؟"),
            ("Where are you from?", "من أين أنت؟"),
            ("I live in Cairo.", "أعيش في القاهرة."),
            ("Nice to meet you.", "سعيد بلقائك."),
            ("This is my brother.", "هذا أخي."),
        ],
        "questions": [
            ("Tell me about your family.", "حدثني عن عائلتك."),
            ("How many brothers and sisters do you have?", "كم أخًا وأختًا لديك؟"),
            ("Who are you closest to in your family?", "من أقرب شخص إليك في العائلة؟"),
            ("Describe your best friend.", "صِف أعز أصدقائك."),
        ],
    },
    {
        "id": "routine", "num": 2,
        "en": "Daily Routine & Time", "ar": "الروتين اليومي والوقت",
        "talk": "تحدث عن يومك المعتاد، ومتى تستيقظ وتنام، وماذا تفعل صباحًا ومساءً.",
        "groups": [
            ("Nouns", "أسماء", [
                ("day", "يوم"), ("morning", "صباح"), ("night", "ليل"),
                ("today", "اليوم"), ("tomorrow", "غدًا"), ("yesterday", "أمس"),
                ("week", "أسبوع"), ("weekend", "نهاية الأسبوع"),
                ("month", "شهر"), ("year", "سنة"), ("hour", "ساعة"),
                ("minute", "دقيقة"), ("moment", "لحظة"), ("time", "وقت"),
                ("watch", "ساعة يد"), ("habit", "عادة"), ("holiday", "عطلة"),
            ]),
            ("Verbs", "أفعال", [
                ("wake up", "يستيقظ"), ("get up", "ينهض"), ("eat", "يأكل"),
                ("drink", "يشرب"), ("wash", "يغسل"), ("work", "يعمل"),
                ("sleep", "ينام"), ("start", "يبدأ"), ("finish", "ينهي"),
                ("go", "يذهب"), ("come", "يأتي"), ("hurry", "يستعجل"),
            ]),
            ("Adjectives", "صفات", [
                ("early", "مبكر"), ("late", "متأخر"), ("busy", "مشغول"),
                ("tired", "متعب"), ("usual", "معتاد"), ("free", "متفرغ"),
            ]),
        ],
        "phrases": [
            ("What time is it?", "كم الساعة؟"),
            ("What time do you wake up?", "متى تستيقظ؟"),
            ("I usually go to bed at 10 pm.", "عادةً أنام الساعة العاشرة مساءً."),
            ("I'm working from home today.", "أعمل من المنزل اليوم."),
            ("See you later.", "أراك لاحقًا."),
        ],
        "questions": [
            ("Describe your typical day.", "صِف يومك المعتاد."),
            ("What time do you wake up and go to sleep?", "متى تستيقظ ومتى تنام؟"),
            ("What do you do in the evening?", "ماذا تفعل في المساء؟"),
            ("Are you a morning person?", "هل أنت شخص صباحي؟"),
        ],
    },
    {
        "id": "home", "num": 3,
        "en": "Home & Living", "ar": "المنزل والسكن",
        "talk": "صِف بيتك وغرفك والأثاث، وقل هل تفضل الشقة أم المنزل.",
        "groups": [
            ("Nouns", "أسماء", [
                ("home", "منزل"), ("house", "بيت"), ("apartment", "شقة"),
                ("room", "غرفة"), ("kitchen", "مطبخ"), ("door", "باب"),
                ("window", "نافذة"), ("wall", "حائط"), ("floor", "أرضية"),
                ("table", "طاولة"), ("chair", "كرسي"), ("bed", "سرير"),
                ("desk", "مكتب"), ("garden", "حديقة"), ("gate", "بوابة"),
                ("basement", "قبو"), ("carpet", "سجادة"), ("blanket", "بطانية"),
                ("lamp", "مصباح"), ("key", "مفتاح"), ("ceiling", "سقف"),
                ("rent", "إيجار"), ("neighbor", "جار"),
            ]),
            ("Verbs", "أفعال", [
                ("live", "يعيش"), ("rent", "يستأجر"), ("clean", "ينظف"),
                ("cook", "يطبخ"), ("build", "يبني"), ("move", "ينتقل"),
                ("open", "يفتح"), ("close", "يغلق"), ("lock", "يقفل"),
            ]),
            ("Adjectives", "صفات", [
                ("big", "كبير"), ("small", "صغير"), ("new", "جديد"),
                ("old", "قديم"), ("comfortable", "مريح"), ("clean", "نظيف"),
                ("expensive", "غالي"), ("cheap", "رخيص"),
            ]),
        ],
        "phrases": [
            ("Where do you live?", "أين تسكن؟"),
            ("I live in an apartment.", "أسكن في شقة."),
            ("Do you have any vacancies?", "هل لديكم غرف شاغرة؟"),
            ("My house has three rooms.", "منزلي فيه ثلاث غرف."),
        ],
        "questions": [
            ("Describe your home.", "صِف منزلك."),
            ("Do you prefer a house or an apartment?", "هل تفضل منزلًا أم شقة؟"),
            ("What's your favorite room and why?", "ما غرفتك المفضلة ولماذا؟"),
            ("Would you like to move to another city?", "هل تود الانتقال إلى مدينة أخرى؟"),
        ],
    },
    {
        "id": "food", "num": 4,
        "en": "Food & Drink", "ar": "الطعام والشراب",
        "talk": "تكلم عن الأكل المفضل، والطبخ، والمطاعم، ووجبات اليوم.",
        "groups": [
            ("Nouns", "أسماء", [
                ("meal", "وجبة"), ("breakfast", "فطور"), ("lunch", "غداء"),
                ("dinner", "عشاء"), ("bread", "خبز"), ("cheese", "جبن"),
                ("egg", "بيضة"), ("fish", "سمك"), ("meat", "لحم"),
                ("fruit", "فاكهة"), ("apple", "تفاحة"), ("vegetable", "خضار"),
                ("salt", "ملح"), ("honey", "عسل"), ("coffee", "قهوة"),
                ("water", "ماء"), ("juice", "عصير"), ("milk", "حليب"),
                ("candy", "حلوى"), ("cake", "كعكة"), ("dish", "طبق"),
                ("taste", "طعم"), ("recipe", "وصفة"), ("menu", "قائمة طعام"),
                ("bottle", "زجاجة"), ("yogurt", "زبادي"),
            ]),
            ("Verbs", "أفعال", [
                ("eat", "يأكل"), ("drink", "يشرب"), ("cook", "يطبخ"),
                ("taste", "يتذوق"), ("order", "يطلب"), ("buy", "يشتري"),
                ("serve", "يقدّم"), ("feed", "يطعم"),
            ]),
            ("Adjectives", "صفات", [
                ("hungry", "جائع"), ("thirsty", "عطشان"),
                ("delicious", "لذيذ"), ("hot", "ساخن"), ("sweet", "حلو"),
                ("bitter", "مرّ"), ("fresh", "طازج"),
            ]),
        ],
        "phrases": [
            ("I'm hungry.", "أنا جائع."),
            ("Can I have the menu, please?", "هل يمكنني الحصول على القائمة من فضلك؟"),
            ("What's for breakfast?", "ماذا يوجد على الفطور؟"),
            ("Can you recommend a restaurant?", "هل يمكنك ترشيح مطعم؟"),
        ],
        "questions": [
            ("What's your favorite food?", "ما طعامك المفضل؟"),
            ("Can you cook? What can you make?", "هل تجيد الطبخ؟ ماذا تستطيع أن تطهو؟"),
            ("Do you prefer eating at home or in restaurants?", "هل تفضل الأكل في المنزل أم في المطاعم؟"),
            ("Describe a traditional dish from your country.", "صِف طبقًا تقليديًا من بلدك."),
        ],
    },
    {
        "id": "shopping", "num": 5,
        "en": "Shopping & Money", "ar": "التسوق والمال",
        "talk": "تحدث عن التسوق، والأسعار، وكيف تدفع وتوفّر المال.",
        "groups": [
            ("Nouns", "أسماء", [
                ("shop", "متجر"), ("market", "سوق"), ("money", "مال"),
                ("price", "سعر"), ("bill", "فاتورة"), ("cash", "نقد"),
                ("card", "بطاقة"), ("change", "فكة / باقي"), ("sale", "تخفيض"),
                ("customer", "زبون"), ("order", "طلب"), ("receipt", "إيصال"),
                ("invoice", "فاتورة"), ("payment", "دفع"), ("bank", "بنك"),
                ("loan", "قرض"), ("bargain", "صفقة"), ("clothes", "ملابس"),
                ("shoes", "أحذية"), ("size", "مقاس"),
            ]),
            ("Verbs", "أفعال", [
                ("buy", "يشتري"), ("sell", "يبيع"), ("pay", "يدفع"),
                ("cost", "يكلف"), ("spend", "ينفق"), ("save", "يوفّر"),
                ("choose", "يختار"), ("afford", "يقدر على شراء"),
            ]),
            ("Adjectives", "صفات", [
                ("cheap", "رخيص"), ("expensive", "غالي"), ("free", "مجاني"),
                ("poor", "فقير"), ("rich", "غني"), ("valuable", "ثمين"),
            ]),
        ],
        "phrases": [
            ("How much is this?", "بكم هذا؟"),
            ("Can I get a refund?", "هل يمكنني استرداد المال؟"),
            ("I'm going to the market.", "سأذهب إلى السوق."),
            ("Do you take cards?", "هل تقبلون البطاقات؟"),
        ],
        "questions": [
            ("Do you like shopping?", "هل تحب التسوق؟"),
            ("Do you prefer online or in-store shopping?", "هل تفضل التسوق عبر الإنترنت أم من المتجر؟"),
            ("How do you save money?", "كيف توفّر المال؟"),
            ("What was the last thing you bought?", "ما آخر شيء اشتريته؟"),
        ],
    },
    {
        "id": "health", "num": 6,
        "en": "Health & The Body", "ar": "الصحة والجسم",
        "talk": "تكلم عن الصحة، وأجزاء الجسم، والذهاب للطبيب، وكيف تحافظ على صحتك.",
        "groups": [
            ("Nouns", "أسماء", [
                ("health", "صحة"), ("body", "جسم"), ("head", "رأس"),
                ("hair", "شعر"), ("eye", "عين"), ("ear", "أذن"),
                ("arm", "ذراع"), ("hand", "يد"), ("leg", "ساق"),
                ("knee", "ركبة"), ("heart", "قلب"), ("blood", "دم"),
                ("bone", "عظم"), ("doctor", "طبيب"), ("nurse", "ممرضة"),
                ("hospital", "مستشفى"), ("pharmacy", "صيدلية"),
                ("medicine", "دواء"), ("disease", "مرض"), ("pain", "ألم"),
                ("emergency", "حالة طوارئ"), ("temperature", "درجة الحرارة"),
            ]),
            ("Verbs", "أفعال", [
                ("feel", "يشعر"), ("hurt", "يؤلم"), ("help", "يساعد"),
                ("rest", "يرتاح"), ("relax", "يسترخي"), ("injure", "يجرح"),
                ("recover", "يتعافى"), ("suffer", "يعاني"),
            ]),
            ("Adjectives", "صفات", [
                ("sick", "مريض"), ("healthy", "صحي / سليم"),
                ("tired", "متعب"), ("weak", "ضعيف"), ("strong", "قوي"),
                ("better", "أفضل"), ("serious", "خطير"),
            ]),
        ],
        "phrases": [
            ("I need to go to the hospital.", "أحتاج للذهاب إلى المستشفى."),
            ("Can you call a doctor?", "هل يمكنك الاتصال بطبيب؟"),
            ("Where is the nearest pharmacy?", "أين أقرب صيدلية؟"),
            ("I don't feel well.", "لا أشعر أنني بخير."),
        ],
        "questions": [
            ("How do you stay healthy?", "كيف تحافظ على صحتك؟"),
            ("Do you exercise regularly?", "هل تمارس الرياضة بانتظام؟"),
            ("When did you last visit a doctor?", "متى زرت الطبيب آخر مرة؟"),
            ("What do you do when you feel stressed?", "ماذا تفعل عندما تشعر بالتوتر؟"),
        ],
    },
    {
        "id": "travel", "num": 7,
        "en": "Travel & Transport", "ar": "السفر والمواصلات",
        "talk": "تحدث عن السفر، ووسائل النقل، والفنادق، وأفضل مكان زرته.",
        "groups": [
            ("Nouns", "أسماء", [
                ("travel", "سفر"), ("journey", "رحلة"), ("trip", "رحلة قصيرة"),
                ("airport", "مطار"), ("plane", "طائرة"), ("train", "قطار"),
                ("bus", "حافلة"), ("car", "سيارة"), ("taxi", "تاكسي"),
                ("ticket", "تذكرة"), ("station", "محطة"), ("hotel", "فندق"),
                ("reservation", "حجز"), ("passport", "جواز سفر"),
                ("map", "خريطة"), ("road", "طريق"), ("direction", "اتجاه"),
                ("distance", "مسافة"), ("luggage", "أمتعة"), ("seat", "مقعد"),
                ("flight", "رحلة جوية"), ("border", "حدود"),
                ("vacation", "إجازة"), ("voyage", "رحلة بحرية"),
            ]),
            ("Verbs", "أفعال", [
                ("travel", "يسافر"), ("arrive", "يصل"), ("leave", "يغادر"),
                ("drive", "يقود"), ("fly", "يطير"), ("visit", "يزور"),
                ("rent", "يستأجر"), ("book", "يحجز"), ("miss", "يفوّت"),
            ]),
            ("Adjectives", "صفات", [
                ("far", "بعيد"), ("near", "قريب"), ("safe", "آمن"),
                ("direct", "مباشر"), ("crowded", "مزدحم"),
            ]),
        ],
        "phrases": [
            ("How can I get to the airport?", "كيف أصل إلى المطار؟"),
            ("I need a taxi.", "أحتاج إلى تاكسي."),
            ("Where is the train station?", "أين محطة القطار؟"),
            ("How long does it take?", "كم يستغرق الوقت؟"),
            ("I lost my passport.", "فقدت جواز سفري."),
        ],
        "questions": [
            ("Do you like traveling?", "هل تحب السفر؟"),
            ("What's the best place you've visited?", "ما أفضل مكان زرته؟"),
            ("How do you usually travel?", "كيف تسافر عادةً؟"),
            ("Where would you like to go next?", "إلى أين تود الذهاب في المرة القادمة؟"),
        ],
    },
    {
        "id": "weather", "num": 8,
        "en": "Weather & Nature", "ar": "الطقس والطبيعة",
        "talk": "صِف الطقس والفصول، والأماكن الطبيعية الجميلة.",
        "groups": [
            ("Nouns", "أسماء", [
                ("weather", "طقس"), ("rain", "مطر"), ("wind", "رياح"),
                ("sun", "شمس"), ("air", "هواء"), ("sky", "سماء"),
                ("cloud", "سحابة"), ("snow", "ثلج"), ("rainbow", "قوس قزح"),
                ("season", "فصل"), ("winter", "شتاء"), ("summer", "صيف"),
                ("storm", "عاصفة"), ("earth", "الأرض"),
                ("earthquake", "زلزال"), ("sea", "بحر"), ("beach", "شاطئ"),
                ("river", "نهر"), ("mountain", "جبل"), ("tree", "شجرة"),
                ("grass", "عشب"), ("animal", "حيوان"), ("bird", "طائر"),
                ("forest", "غابة"), ("nature", "طبيعة"), ("valley", "واد"),
            ]),
            ("Verbs", "أفعال", [
                ("rain", "تمطر"), ("shine", "تسطع"), ("grow", "ينمو"),
                ("blow", "تهبّ"),
            ]),
            ("Adjectives", "صفات", [
                ("hot", "حار"), ("cold", "بارد"), ("warm", "دافئ"),
                ("wet", "مبتل"), ("dry", "جاف"), ("cloudy", "غائم"),
                ("sunny", "مشمس"), ("natural", "طبيعي"), ("wild", "برّي"),
            ]),
        ],
        "phrases": [
            ("What's the weather like today?", "كيف الطقس اليوم؟"),
            ("It's raining today.", "الجو ممطر اليوم."),
            ("It's very hot in summer.", "الجو حار جدًا في الصيف."),
        ],
        "questions": [
            ("What's the weather like in your city?", "كيف الطقس في مدينتك؟"),
            ("What's your favorite season?", "ما فصلك المفضل؟"),
            ("Do you prefer summer or winter?", "هل تفضل الصيف أم الشتاء؟"),
            ("Describe a beautiful place in nature.", "صِف مكانًا طبيعيًا جميلًا."),
        ],
    },
    {
        "id": "hobbies", "num": 9,
        "en": "Free Time & Hobbies", "ar": "وقت الفراغ والهوايات",
        "talk": "تكلم عن هواياتك، والموسيقى، والأفلام، والرياضة في وقت فراغك.",
        "groups": [
            ("Nouns", "أسماء", [
                ("hobby", "هواية"), ("game", "لعبة"), ("music", "موسيقى"),
                ("movie", "فيلم"), ("book", "كتاب"), ("sport", "رياضة"),
                ("football", "كرة قدم"), ("party", "حفلة"),
                ("festival", "مهرجان"), ("holiday", "عطلة"),
                ("guitar", "جيتار"), ("art", "فن"), ("photo", "صورة"),
                ("camera", "كاميرا"), ("gym", "صالة رياضية"), ("story", "قصة"),
            ]),
            ("Verbs", "أفعال", [
                ("play", "يلعب"), ("watch", "يشاهد"), ("listen", "يستمع"),
                ("read", "يقرأ"), ("sing", "يغني"), ("dance", "يرقص"),
                ("enjoy", "يستمتع"), ("relax", "يسترخي"), ("paint", "يرسم"),
            ]),
            ("Adjectives", "صفات", [
                ("fun", "ممتع"), ("interesting", "مثير للاهتمام"),
                ("boring", "ممل"), ("favorite", "مفضل"), ("popular", "مشهور"),
            ]),
        ],
        "phrases": [
            ("I like watching movies.", "أحب مشاهدة الأفلام."),
            ("Do you have any hobbies?", "هل لديك هوايات؟"),
            ("I play football every weekend.", "ألعب كرة القدم كل نهاية أسبوع."),
        ],
        "questions": [
            ("What do you do in your free time?", "ماذا تفعل في وقت فراغك؟"),
            ("What kind of music do you like?", "أي نوع من الموسيقى تحب؟"),
            ("What's your favorite movie?", "ما فيلمك المفضل؟"),
            ("Do you play any sports?", "هل تمارس أي رياضة؟"),
        ],
    },
    {
        "id": "tech", "num": 10,
        "en": "Technology & Communication", "ar": "التكنولوجيا والتواصل",
        "talk": "تحدث عن الهاتف، والإنترنت، والتطبيقات، ودور التكنولوجيا في حياتك.",
        "groups": [
            ("Nouns", "أسماء", [
                ("phone", "هاتف"), ("computer", "حاسوب"),
                ("laptop", "حاسوب محمول"), ("internet", "إنترنت"),
                ("email", "بريد إلكتروني"), ("message", "رسالة"),
                ("website", "موقع إلكتروني"), ("screen", "شاشة"),
                ("keyboard", "لوحة مفاتيح"), ("mouse", "فأرة"),
                ("network", "شبكة"), ("app", "تطبيق"), ("video", "فيديو"),
                ("information", "معلومات"), ("news", "أخبار"),
                ("technology", "تقنية"), ("device", "جهاز"),
                ("printer", "طابعة"), ("data", "بيانات"),
            ]),
            ("Verbs", "أفعال", [
                ("call", "يتصل"), ("send", "يرسل"), ("receive", "يستلم"),
                ("use", "يستخدم"), ("download", "يحمّل"), ("search", "يبحث"),
                ("update", "يحدّث"), ("connect", "يتصل / يربط"),
                ("install", "يثبّت"),
            ]),
            ("Adjectives", "صفات", [
                ("online", "متصل بالإنترنت"), ("digital", "رقمي"),
                ("modern", "حديث"), ("useful", "مفيد"),
                ("virtual", "افتراضي"),
            ]),
        ],
        "phrases": [
            ("What's your phone number?", "ما رقم هاتفك؟"),
            ("Can you send me an email?", "هل يمكنك إرسال بريد إلكتروني لي؟"),
            ("Is there Wi-Fi here?", "هل يوجد واي فاي هنا؟"),
            ("Where can I buy a SIM card?", "أين يمكنني شراء شريحة هاتف؟"),
        ],
        "questions": [
            ("How much time do you spend on your phone?", "كم من الوقت تقضيه على هاتفك؟"),
            ("What apps do you use most?", "ما التطبيقات التي تستخدمها أكثر؟"),
            ("Is technology good or bad for us?", "هل التكنولوجيا مفيدة أم مضرة لنا؟"),
            ("Could you live without the internet?", "هل تستطيع العيش دون إنترنت؟"),
        ],
    },
    {
        "id": "feelings", "num": 11,
        "en": "Feelings, Personality & People", "ar": "المشاعر والشخصية ووصف الناس",
        "talk": "عبّر عن مشاعرك، وصِف شخصيتك وشخصيات الناس ومظهرهم.",
        "groups": [
            ("Nouns", "أسماء", [
                ("feeling", "شعور"), ("emotion", "عاطفة"), ("fear", "خوف"),
                ("joy", "فرح"), ("love", "حب"), ("hope", "أمل"),
                ("humor", "فكاهة"), ("ambition", "طموح"),
                ("attitude", "سلوك / موقف"), ("behavior", "سلوك"),
                ("character", "شخصية"), ("appearance", "مظهر"),
                ("beauty", "جمال"),
            ]),
            ("Verbs", "أفعال", [
                ("feel", "يشعر"), ("love", "يحب"), ("hate", "يكره"),
                ("hope", "يأمل"), ("worry", "يقلق"), ("enjoy", "يستمتع"),
                ("care", "يهتم"), ("laugh", "يضحك"), ("cry", "يبكي"),
            ]),
            ("Adjectives", "صفات", [
                ("happy", "سعيد"), ("sad", "حزين"), ("angry", "غاضب"),
                ("afraid", "خائف"), ("excited", "متحمس"), ("calm", "هادئ"),
                ("kind", "لطيف"), ("honest", "صادق"), ("brave", "شجاع"),
                ("jealous", "غيور"), ("serious", "جاد"),
                ("friendly", "ودود"), ("patient", "صبور"), ("lazy", "كسول"),
                ("polite", "مؤدب"), ("shy", "خجول"), ("confident", "واثق"),
                ("tall", "طويل"), ("short", "قصير"), ("beautiful", "جميل"),
            ]),
        ],
        "phrases": [
            ("How are you?", "كيف حالك؟"),
            ("I'm very happy today.", "أنا سعيد جدًا اليوم."),
            ("I feel a little tired.", "أشعر بتعب قليل."),
            ("He is a very kind person.", "إنه شخص لطيف جدًا."),
        ],
        "questions": [
            ("How do you feel today?", "كيف تشعر اليوم؟"),
            ("Describe your personality.", "صِف شخصيتك."),
            ("What makes you happy?", "ما الذي يجعلك سعيدًا؟"),
            ("How do you deal with stress?", "كيف تتعامل مع التوتر؟"),
        ],
    },
    {
        "id": "education", "num": 12,
        "en": "Education & Learning", "ar": "التعليم والدراسة",
        "talk": "تحدث عن دراستك، وتعلّم اللغات، والمواد، والامتحانات.",
        "groups": [
            ("Nouns", "أسماء", [
                ("school", "مدرسة"), ("university", "جامعة"),
                ("student", "طالب"), ("teacher", "معلم"), ("lesson", "درس"),
                ("class", "حصة / صف"), ("exam", "امتحان"), ("test", "اختبار"),
                ("homework", "واجب"), ("book", "كتاب"), ("subject", "مادة"),
                ("topic", "موضوع"), ("library", "مكتبة"),
                ("knowledge", "معرفة"), ("science", "علم"),
                ("language", "لغة"), ("degree", "شهادة"), ("grade", "درجة"),
                ("skill", "مهارة"), ("education", "تعليم"),
                ("question", "سؤال"), ("answer", "إجابة"), ("mistake", "خطأ"),
            ]),
            ("Verbs", "أفعال", [
                ("study", "يدرس"), ("learn", "يتعلم"), ("teach", "يعلّم"),
                ("read", "يقرأ"), ("write", "يكتب"), ("understand", "يفهم"),
                ("remember", "يتذكر"), ("forget", "ينسى"), ("explain", "يشرح"),
                ("pass", "ينجح"), ("fail", "يرسب"), ("improve", "يحسّن"),
                ("practice", "يتمرن"),
            ]),
            ("Adjectives", "صفات", [
                ("easy", "سهل"), ("difficult", "صعب"), ("clever", "ذكي"),
                ("important", "مهم"), ("useful", "مفيد"),
            ]),
        ],
        "phrases": [
            ("Where do you study?", "أين تدرس؟"),
            ("What's your major?", "ما تخصصك؟"),
            ("I need to improve my English.", "أحتاج إلى تحسين لغتي الإنجليزية."),
            ("I passed the exam.", "نجحت في الامتحان."),
        ],
        "questions": [
            ("What are you studying?", "ماذا تدرس؟"),
            ("Why are you learning English?", "لماذا تتعلم الإنجليزية؟"),
            ("What was your favorite subject at school?", "ما مادتك المفضلة في المدرسة؟"),
            ("Do you prefer studying alone or with others?", "هل تفضل الدراسة وحدك أم مع الآخرين؟"),
        ],
    },
    {
        "id": "work", "num": 13,
        "en": "Work & Jobs", "ar": "العمل والوظائف",
        "talk": "تكلم عن عملك أو وظيفة أحلامك، وزملائك، ومكان عملك. (مفردات أساسية للعمل)",
        "groups": [
            ("Nouns", "أسماء", [
                ("job", "وظيفة"), ("work", "عمل"), ("company", "شركة"),
                ("office", "مكتب"), ("manager", "مدير"),
                ("employee", "موظف"), ("colleague", "زميل"), ("boss", "رئيس"),
                ("department", "قسم"), ("meeting", "اجتماع"),
                ("report", "تقرير"), ("task", "مهمة"), ("project", "مشروع"),
                ("client", "عميل"), ("customer", "زبون"), ("salary", "راتب"),
                ("career", "مسيرة مهنية"), ("position", "منصب"),
                ("deadline", "موعد نهائي"), ("break", "استراحة"),
                ("contract", "عقد"), ("interview", "مقابلة"),
                ("business", "عمل / تجارة"),
            ]),
            ("Verbs", "أفعال", [
                ("work", "يعمل"), ("manage", "يدير"), ("help", "يساعد"),
                ("call", "يتصل"), ("send", "يرسل"), ("meet", "يقابل"),
                ("prepare", "يجهّز"), ("finish", "ينهي"), ("plan", "يخطط"),
                ("organize", "ينظّم"), ("complete", "يكمل"), ("check", "يفحص"),
            ]),
            ("Adjectives", "صفات", [
                ("busy", "مشغول"), ("hard", "صعب"),
                ("professional", "احترافي"), ("full-time", "دوام كامل"),
                ("part-time", "دوام جزئي"),
            ]),
        ],
        "phrases": [
            ("What do you do for work?", "ماذا تعمل؟"),
            ("I work as a teacher.", "أعمل معلمًا."),
            ("Do you like your job?", "هل تحب عملك؟"),
            ("I'm looking for a new job.", "أبحث عن وظيفة جديدة."),
        ],
        "questions": [
            ("What do you do for a living?", "ماذا تعمل لكسب رزقك؟"),
            ("Do you like your job? Why?", "هل تحب عملك؟ لماذا؟"),
            ("Describe your workplace.", "صِف مكان عملك."),
            ("What's your dream job?", "ما وظيفة أحلامك؟"),
        ],
    },
    {
        "id": "office", "num": 14,
        "en": "The Office, Meetings & Email", "ar": "المكتب والاجتماعات والمراسلات",
        "talk": "مفردات العمل لمستوى B1: الاجتماعات، والبريد، والمهام، والعمل الجماعي.",
        "level": "B1",
        "groups": [
            ("Nouns", "أسماء", [
                ("meeting", "اجتماع"), ("agenda", "جدول أعمال"),
                ("presentation", "عرض تقديمي"), ("report", "تقرير"),
                ("email", "بريد إلكتروني"), ("document", "مستند"),
                ("file", "ملف"), ("form", "استمارة"), ("schedule", "جدول"),
                ("appointment", "موعد"), ("feedback", "تغذية راجعة"),
                ("request", "طلب"), ("notice", "إشعار"),
                ("deadline", "موعد نهائي"), ("minutes", "محضر اجتماع"),
                ("supervisor", "مشرف"), ("teamwork", "عمل جماعي"),
                ("responsibility", "مسؤولية"), ("progress", "تقدّم"),
            ]),
            ("Verbs (B1)", "أفعال (B1)", [
                ("arrange", "يرتب"), ("attend", "يحضر"), ("discuss", "يناقش"),
                ("confirm", "يؤكد"), ("contact", "يتواصل"),
                ("coordinate", "ينسّق"), ("inform", "يبلّغ"),
                ("schedule", "يحدد موعدًا"), ("present", "يقدّم"),
                ("submit", "يقدّم / يسلّم"), ("review", "يراجع"),
                ("respond", "يستجيب"), ("mention", "يذكر"),
                ("monitor", "يراقب"), ("participate", "يشارك"),
                ("share", "يشارك"), ("update", "يحدّث"),
            ]),
            ("Adjectives", "صفات", [
                ("available", "متاح"), ("urgent", "عاجل"),
                ("important", "مهم"), ("responsible", "مسؤول"),
            ]),
        ],
        "phrases": [
            ("When is the deadline?", "متى الموعد النهائي؟"),
            ("Let's discuss this later.", "دعنا نناقش هذا لاحقًا."),
            ("Do you have any questions?", "هل لديك أي أسئلة؟"),
            ("I need to prepare a presentation.", "أحتاج إلى تحضير عرض تقديمي."),
        ],
        "questions": [
            ("Describe a typical meeting at work.", "صِف اجتماعًا معتادًا في العمل."),
            ("How do you organize your tasks?", "كيف تنظّم مهامك؟"),
            ("Do you prefer email or phone calls at work?", "هل تفضل البريد أم المكالمات في العمل؟"),
            ("How do you work in a team?", "كيف تعمل ضمن فريق؟"),
        ],
    },
    {
        "id": "career", "num": 15,
        "en": "Professional Skills & Career", "ar": "المهارات المهنية والمسيرة المهنية",
        "talk": "مفردات متقدمة (B2) لتطوير حديثك: القيادة، والمهارات، والأهداف. مفيدة لرفع مستواك.",
        "level": "B2",
        "groups": [
            ("Nouns", "أسماء", [
                ("leadership", "قيادة"), ("experience", "خبرة"),
                ("skill", "مهارة"), ("goal", "هدف"),
                ("achievement", "إنجاز"), ("promotion", "ترقية"),
                ("performance", "أداء"), ("quality", "جودة"),
                ("strategy", "استراتيجية"), ("opportunity", "فرصة"),
                ("challenge", "تحدٍّ"), ("training", "تدريب"),
                ("development", "تطوير"), ("budget", "ميزانية"),
                ("problem-solving", "حل المشكلات"),
                ("decision-making", "اتخاذ القرار"),
                ("time management", "إدارة الوقت"),
            ]),
            ("Verbs (B2)", "أفعال (B2)", [
                ("achieve", "يحقق"), ("improve", "يحسّن"), ("lead", "يقود"),
                ("develop", "يطوّر"), ("solve", "يحل"),
                ("negotiate", "يتفاوض"), ("supervise", "يشرف"),
                ("motivate", "يحفّز"), ("collaborate", "يتعاون"),
                ("prioritize", "يحدد الأولويات"), ("implement", "يطبّق"),
                ("evaluate", "يقيّم"), ("communicate", "يتواصل"),
                ("delegate", "يفوّض"),
            ]),
            ("Adjectives", "صفات", [
                ("professional", "احترافي"), ("responsible", "مسؤول"),
                ("efficient", "كفء"), ("reliable", "موثوق"),
                ("confident", "واثق"), ("ambitious", "طموح"),
                ("organized", "منظّم"),
            ]),
        ],
        "phrases": [
            ("What skills do you have?", "ما المهارات التي تملكها؟"),
            ("I want to develop my career.", "أريد أن أطوّر مسيرتي المهنية."),
            ("Teamwork is very important.", "العمل الجماعي مهم جدًا."),
        ],
        "questions": [
            ("What are your strengths and weaknesses?", "ما نقاط قوتك وضعفك؟"),
            ("Where do you see yourself in five years?", "أين ترى نفسك بعد خمس سنوات؟"),
            ("What skills are important for your job?", "ما المهارات المهمة لعملك؟"),
            ("Tell me about an achievement you're proud of.", "حدثني عن إنجاز تفخر به."),
        ],
    },
]

# base - past - past participle - meaning
VERBS3 = [
    ("be", "was / were", "been", "يكون"),
    ("have", "had", "had", "يملك / لديه"),
    ("do", "did", "done", "يفعل"),
    ("say", "said", "said", "يقول"),
    ("go", "went", "gone", "يذهب"),
    ("get", "got", "gotten / got", "يحصل على"),
    ("make", "made", "made", "يصنع"),
    ("know", "knew", "known", "يعرف"),
    ("think", "thought", "thought", "يفكر"),
    ("take", "took", "taken", "يأخذ"),
    ("see", "saw", "seen", "يرى"),
    ("come", "came", "come", "يأتي"),
    ("find", "found", "found", "يجد"),
    ("give", "gave", "given", "يعطي"),
    ("tell", "told", "told", "يخبر"),
    ("become", "became", "become", "يصبح"),
    ("leave", "left", "left", "يغادر"),
    ("feel", "felt", "felt", "يشعر"),
    ("bring", "brought", "brought", "يحضر"),
    ("begin", "began", "begun", "يبدأ"),
    ("keep", "kept", "kept", "يحتفظ"),
    ("write", "wrote", "written", "يكتب"),
    ("stand", "stood", "stood", "يقف"),
    ("hear", "heard", "heard", "يسمع"),
    ("mean", "meant", "meant", "يعني"),
    ("meet", "met", "met", "يلتقي"),
    ("run", "ran", "run", "يجري"),
    ("pay", "paid", "paid", "يدفع"),
    ("sit", "sat", "sat", "يجلس"),
    ("speak", "spoke", "spoken", "يتحدث"),
    ("lose", "lost", "lost", "يخسر"),
    ("send", "sent", "sent", "يرسل"),
    ("build", "built", "built", "يبني"),
    ("understand", "understood", "understood", "يفهم"),
    ("buy", "bought", "bought", "يشتري"),
    ("teach", "taught", "taught", "يدرّس"),
    ("catch", "caught", "caught", "يمسك"),
    ("drive", "drove", "driven", "يقود"),
    ("eat", "ate", "eaten", "يأكل"),
    ("fall", "fell", "fallen", "يسقط"),
    ("read", "read", "read", "يقرأ"),
    ("sell", "sold", "sold", "يبيع"),
    ("sleep", "slept", "slept", "ينام"),
    ("break", "broke", "broken", "يكسر"),
    ("choose", "chose", "chosen", "يختار"),
    ("draw", "drew", "drawn", "يرسم"),
    ("grow", "grew", "grown", "ينمو"),
    ("win", "won", "won", "يفوز"),
    ("wear", "wore", "worn", "يرتدي"),
    ("forget", "forgot", "forgotten", "ينسى"),
    ("cut", "cut", "cut", "يقطع"),
    ("put", "put", "put", "يضع"),
]

# en name, ar name, use(ar), structure, examples
TENSES = [
    ("Present Simple", "المضارع البسيط", "الحقائق والعادات والجداول الزمنية",
     "Subject + base verb (+ s/es for he/she/it)",
     ["I work every day.", "She works at 9 o'clock."]),
    ("Present Continuous", "المضارع المستمر", "حدث يحدث الآن أو خطة مستقبلية",
     "Subject + am / is / are + verb-ing",
     ["I am working now.", "They are coming tomorrow."]),
    ("Past Simple", "الماضي البسيط", "حدث أو عادة في الماضي انتهت",
     "Subject + verb-ed (or 2nd form)",
     ["I visited my friend yesterday.", "She went to school last week."]),
    ("Past Continuous", "الماضي المستمر", "حدث كان مستمرًا في وقت معيّن في الماضي",
     "Subject + was / were + verb-ing",
     ["I was studying at 8 pm.", "They were playing football."]),
    ("Present Perfect", "المضارع التام", "حدث بدأ في الماضي وأثره موجود الآن",
     "Subject + have / has + past participle",
     ["I have lived here for five years.", "She has finished her work."]),
    ("Present Perfect Continuous", "المضارع التام المستمر",
     "حدث بدأ في الماضي واستمر لفترة حتى الآن",
     "Subject + have / has been + verb-ing",
     ["I have been studying for two hours.", "They have been waiting since morning."]),
    ("Past Perfect", "الماضي التام", "حدث وقع قبل حدث آخر في الماضي",
     "Subject + had + past participle",
     ["I had eaten before he arrived.", "She had left when I called."]),
    ("Past Perfect Continuous", "الماضي التام المستمر",
     "حدث مستمر وقع قبل وقت معيّن في الماضي",
     "Subject + had been + verb-ing",
     ["I had been working for 2 hours when he came."]),
    ("Future Simple", "المستقبل البسيط", "قرار أو توقّع أو وعد",
     "Subject + will + base verb",
     ["I will call you later.", "They will come tomorrow."]),
    ("Be going to", "التعبير عن النية والخطط", "النية أو الخطط المستقبلية",
     "Subject + am / is / are + going to + base verb",
     ["I am going to travel next week.", "She is going to study medicine."]),
    ("Future Continuous", "المستقبل المستمر", "حدث مستمر في وقت معيّن في المستقبل",
     "Subject + will be + verb-ing",
     ["I will be working at 10 am tomorrow."]),
]

TO_INF = [
    ("want", "I want to go."), ("need", "You need to study."),
    ("hope", "They hope to win."), ("plan", "We plan to travel."),
    ("decide", "He decided to leave."), ("learn", "She's learning to drive."),
    ("promise", "I promise to help."), ("agree", "He agreed to come."),
    ("expect", "I expect to pass."), ("offer", "They offered to pay."),
    ("refuse", "She refused to go."), ("would like", "I'd like to eat."),
    ("manage", "He managed to finish."), ("afford", "I can't afford to buy it."),
    ("pretend", "She pretended to sleep."),
]

GERUND = [
    ("enjoy", "I enjoy reading."), ("avoid", "He avoids driving."),
    ("finish", "She finished cleaning."), ("keep", "Keep going."),
    ("suggest", "I suggest waiting."), ("recommend", "They recommend trying it."),
    ("mind", "Do you mind closing the door?"), ("consider", "We considered moving."),
    ("deny", "He denied stealing."), ("miss", "I miss talking to you."),
    ("practice", "She practiced singing."), ("imagine", "Imagine living there."),
    ("risk", "He risked losing everything."), ("postpone", "They postponed meeting."),
]

BOTH_PATTERN = [
    ("remember", "I remembered to lock the door.", "تذكّرت أن أقفل الباب (قبل أن أفعلها)."),
    ("remember", "I remember locking the door.", "أتذكّر أنني قفلت الباب (فعلتها بالفعل)."),
]

EXPRESSIONS = [
    ("be used to", "معتاد على"), ("look forward to", "يتطلع إلى"),
    ("be interested in", "مهتم بـ"),
]

PHRASE_SITUATIONS = [
    ("Greetings & Basics", "تحيات وأساسيات", [
        ("Hello!", "مرحبًا!"),
        ("How are you?", "كيف حالك؟"),
        ("Nice to meet you.", "سعيد بلقائك."),
        ("What do you do?", "ماذا تعمل؟"),
        ("Can you help me?", "هل يمكنك مساعدتي؟"),
        ("I don't understand.", "لا أفهم."),
        ("Please speak slowly.", "من فضلك تحدث ببطء."),
        ("Thank you!", "شكرًا!"),
        ("You're welcome.", "على الرحب والسعة."),
        ("Excuse me.", "عفوًا."),
        ("I'm sorry.", "أنا آسف."),
        ("Do you speak English?", "هل تتكلم الإنجليزية؟"),
        ("Can you repeat that?", "هل يمكنك تكرار ذلك؟"),
        ("How do you say this in English?", "كيف تقول هذا بالإنجليزية؟"),
    ]),
    ("Travel & Directions", "السفر والاتجاهات", [
        ("How can I get to the airport?", "كيف أصل إلى المطار؟"),
        ("Where is the train station?", "أين محطة القطار؟"),
        ("How long does it take?", "كم يستغرق الوقت؟"),
        ("I need a taxi.", "أحتاج إلى تاكسي."),
        ("I have a reservation.", "لديّ حجز."),
        ("Where is the hotel?", "أين الفندق؟"),
        ("Is breakfast included?", "هل الإفطار متضمَّن؟"),
        ("Can you show me on the map?", "هل يمكنك أن تريني على الخريطة؟"),
        ("I lost my passport.", "فقدت جواز سفري."),
        ("What is the emergency number?", "ما رقم الطوارئ؟"),
    ]),
    ("Work & Study", "العمل والدراسة", [
        ("What do you do for work?", "ماذا تعمل؟"),
        ("I work as a teacher.", "أعمل معلمًا."),
        ("Where do you study?", "أين تدرس؟"),
        ("What's your major?", "ما تخصصك؟"),
        ("When is the deadline?", "متى الموعد النهائي؟"),
        ("I have a meeting at 3 pm.", "لديّ اجتماع الساعة الثالثة مساءً."),
        ("Let's discuss this later.", "دعنا نناقش هذا لاحقًا."),
        ("I'm looking for a new job.", "أبحث عن وظيفة جديدة."),
        ("Can you explain this topic?", "هل يمكنك شرح هذا الموضوع؟"),
        ("I passed the exam.", "نجحت في الامتحان."),
    ]),
    ("Everyday Situations", "مواقف يومية", [
        ("How much is this?", "بكم هذا؟"),
        ("What time is it?", "كم الساعة؟"),
        ("I'm hungry.", "أنا جائع."),
        ("I'm going to the market.", "سأذهب إلى السوق."),
        ("It's raining today.", "الجو ممطر اليوم."),
        ("I like watching movies.", "أحب مشاهدة الأفلام."),
        ("Do you have any hobbies?", "هل لديك هوايات؟"),
        ("Let's meet tomorrow.", "لنلتقِ غدًا."),
    ]),
]

# word, synonyms, arabic
SYNONYMS = [
    ("company", "firm, business, organization", "شركة، مؤسسة، منظمة"),
    ("office", "workplace, bureau", "مكان العمل، مكتب"),
    ("manager", "supervisor, head", "مشرف، رئيس"),
    ("employee", "staff, worker", "موظف، عامل"),
    ("meeting", "gathering, conference", "اجتماع، مؤتمر"),
    ("report", "account, summary", "تقرير، ملخص"),
    ("task", "duty, assignment", "مهمة، واجب"),
    ("client", "customer, patron", "زبون، مستفيد"),
    ("project", "plan, scheme", "خطة، مشروع"),
    ("job", "position, role", "وظيفة، منصب"),
    ("achievement", "accomplishment, success", "إنجاز، نجاح"),
    ("adjustment", "modification, change", "تعديل، تغيير"),
    ("analysis", "examination, study", "فحص، دراسة"),
    ("approval", "authorization, consent", "تفويض، موافقة"),
    ("assessment", "evaluation, appraisal", "تقييم، مراجعة"),
    ("attendance", "presence, participation", "حضور، مشاركة"),
    ("ability", "capability, skill", "قدرة، مهارة"),
    ("collaboration", "cooperation, partnership", "تعاون، شراكة"),
    ("communication", "interaction, correspondence", "تواصل، مراسلة"),
    ("complaint", "grievance, objection", "شكوى، اعتراض"),
    ("concept", "idea, notion", "فكرة، مفهوم"),
    ("conclusion", "deduction, result", "استنتاج، نتيجة"),
    ("contract", "agreement, deal", "اتفاقية، صفقة"),
    ("accuracy", "precision, exactness", "دقة، صحة"),
    ("administration", "management, supervision", "إدارة، إشراف"),
    ("advancement", "promotion, progress", "ترقية، تقدم"),
    ("clarification", "explanation, elaboration", "توضيح، تفصيل"),
    ("commitment", "dedication, obligation", "التزام، واجب"),
    ("credibility", "reliability, trustworthiness", "مصداقية، موثوقية"),
    ("delivery", "distribution, conveyance", "توزيع، إيصال"),
    ("efficiency", "effectiveness, productivity", "فاعلية، إنتاجية"),
    ("development", "growth, progress", "نمو، تقدم"),
]
